apiVersion: apps/v1
kind: Deployment
metadata:
  name: hxx
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hxx
  template:
    metadata:
      labels:
        name: hxx
    spec:
      restartPolicy: Always
      containers:
        - name: hxx
          image: kinhanlin/hxx:v1.6
          ports:
            - containerPort: 8080
            
---
apiVersion: v1
kind: Service
metadata:
  name: hxx
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "hxx"
    port: 8080
  selector:
    name: hxx
